OUTPUT_FILE_PREFIX = 'stego_'
OUTPUT_KEY_PREFIX = 'personal_key_'
ALTER_PERCENT_LSB_KEY_BASED = 0.5
FREQUENCY_EMBED_EVERY_SAMPLES = 100
FREQUENCY_TO_HIDE_ON = 20100 # humans hear frequencies between 20hz-20000hz